console.log("This is tut11");
let a = window.document;
// window.alert("Hello anjali");
// a = prompt("This will destroy your computer");
// a = confirm("Are you sure you want to delete this page?");
// a = window.innerHeight;  
// a =innerWidth; 
// a = scrollY;
// a = location.toString();
a = window.history;
console.log(a);
